const AppImages = {
  background: require('../../assets/images/background.png'),
  backgroundRegister: require('../../assets/images/background_register.png'),
  posters: {
    dune: require('../../assets/images/posters/dune.png'),
  },
  addProfile: require('../../assets/images/add/add.png'),
  logoNetflix: require('../../assets/images/logo_netflix.png'),
  nNetflix: require('../../assets/images/nnetflix/nnetflix.png'),
  profiles: {
    blue: require('../../assets/images/profiles/blue/blue.png'),
    pink: require('../../assets/images/profiles/pink/pink.png'),
    yellow: require('../../assets/images/profiles/yellow/yellow.png'),
    green: require('../../assets/images/profiles/green/green.png'),
  },
  landscape_thumbnails: {
    attackOnPearlHarbour: require('../../assets/images/landscape_thumbnails/attack_on_pearl_harbour/attack_on_pearl_harbour.png'),
    blonde: require('../../assets/images/landscape_thumbnails/blonde/blonde.png'),
    dangerousLiasons: require('../../assets/images/landscape_thumbnails/dangerous_liasons/dangerous_liasons.png'),
    halftime: require('../../assets/images/landscape_thumbnails/halftime/halftime.png'),
    heat: require('../../assets/images/landscape_thumbnails/heat/heat.png'),
    hustle: require('../../assets/images/landscape_thumbnails/hustle/hustle.png'),
    keepSweetPrayAndObey: require('../../assets/images/landscape_thumbnails/keep_sweet_pray_and_obey/keep_sweet_pray_and_obey.png'),
    peakyBlinders: require('../../assets/images/landscape_thumbnails/peaky_blinders/peaky_blinders.png'),
    theArtOfIncarceration: require('../../assets/images/landscape_thumbnails/the_art_of_incarceration/the_art_of_incarceration.png'),
    theGirlInThePicture: require('../../assets/images/landscape_thumbnails/the_girl_in_the_picture/the_girl_in_the_picture.png'),
    theGrayMan: require('../../assets/images/landscape_thumbnails/the_gray_man/the_gray_man.png'),
    theKingOfStatenIsland: require('../../assets/images/landscape_thumbnails/the_king_of_staten_island/the_king_of_staten_island.png'),
    theSeaBeast: require('../../assets/images/landscape_thumbnails/the_sea_beast/the_sea_beast.png'),
    theUmbrellaAcademy: require('../../assets/images/landscape_thumbnails/the_umbrella_academy/the_umbrella_academy.png'),
  },
  portrait_thumbnails: {
    blasted: require('../../assets/images/portrait_thumbnails/blasted/blasted.png'),
    hustle: require('../../assets/images/portrait_thumbnails/hustle/hustle.png'),
    ironChef: require('../../assets/images/portrait_thumbnails/iron_chef/iron_chef.png'),
    loveAndGelato: require('../../assets/images/portrait_thumbnails/love_and_gelato/love_and_gelato.png'),
    manVsBee: require('../../assets/images/portrait_thumbnails/man_vs_bee/man_vs_bee.png'),
    moneyHeist: require('../../assets/images/portrait_thumbnails/money_heist/money_heist.png'),
    peakyBlinders: require('../../assets/images/portrait_thumbnails/peaky_blinders/peaky_blinders.png'),
    snowflakeMountain: require('../../assets/images/portrait_thumbnails/snowflake_mountain/snowflake_mountain.png'),
    spiderhead: require('../../assets/images/portrait_thumbnails/spiderhead/spiderhead.png'),
    strangerThings: require('../../assets/images/portrait_thumbnails/stranger_things/stranger_things.png'),
    theSecretLifeOfPets: require('../../assets/images/portrait_thumbnails/the_secret_life_of_pets/the_secret_life_of_pets.png'),
    theLincolnLawyer: require('../../assets/images/portrait_thumbnails/the_lincoln_lawyer/the_lincoln_lawyer.png'),
    theManFromToronto: require('../../assets/images/portrait_thumbnails/the_man_from_toronto/the_man_from_toronto.png'),
    theUmbrellaAcademy: require('../../assets/images/portrait_thumbnails/the_umbrella_academy/the_umbrella_academy.png'),
    madameWeb: require('../../assets/images/portrait_thumbnails/madame_web/madame_web.png'),
    ourBelovedSummer: require('../../assets/images/portrait_thumbnails/our_beloved_summer/our_beloved_summer.png'),
  },
};

export default AppImages;
