const AppIcons = {
  plus: require('../../assets/icons/plus/plus.png'),
  arrow_left: require('../../assets/icons/arrow_left/arrow_left.png'),
  x_circle: require('../../assets/icons/x_circle/x_circle.png'),
  screen_cast: require('../../assets/icons/screen_cast/screen_cast.png'),
  warning_circle: require('../../assets/icons/warning_circle/warning_circle.png'),
  pen: require('../../assets/icons/pen/pen.png'),
  caret_down: require('../../assets/icons/caret_down/caret_down.png'),
  x: require('../../assets/icons/x/x.png'),
  thumbs_up: require('../../assets/icons/thumbs_up/thumbs_up.png'),
  paper_plane_tilt: require('../../assets/icons/paper_plane_tilt/paper_plane_tilt.png'),
  home: require('../../assets/icons/home/home.png'),
  home_active: require('../../assets/icons/home/active.png'),
  search: require('../../assets/icons/search/search.png'),
  search_active: require('../../assets/icons/search/active.png'),
  download: require('../../assets/icons/download/download.png'),
  download_active: require('../../assets/icons/download/active.png'),
  more: require('../../assets/icons/more/more.png'),
  more_active: require('../../assets/icons/more/active.png'),
  media: require('../../assets/icons/media/media.png'),
  media_active: require('../../assets/icons/media/active.png'),
  eye: require('../../assets/icons/eye/eye.png'),
  eye_slash: require('../../assets/icons/eye_slash/eye_slash.png'),
  dark_eye: require('../../assets/icons/eye/dark/eye.png'),
  dark_eye_slash: require('../../assets/icons/eye_slash/dark/eye_slash.png'),
  play: require('../../assets/icons/play/play.png'),
};

export default AppIcons;
